FROM node:22-bookworm-slim

WORKDIR /app

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN corepack enable && corepack prepare pnpm@10.14.0 --activate

COPY . .

RUN pnpm install --frozen-lockfile
RUN pnpm build:all

EXPOSE 3000 3010

CMD ["pnpm", "start:prod"]
