#!/usr/bin/env bash
set -euo pipefail

DEFAULT_DATABASE_URL="postgresql://agentif:agentif@172.20.0.1:5432/agentifui"
DEFAULT_S3_ENDPOINT="http://172.20.0.1:9000"

export M7_TARGET_DATABASE_URL="${M7_TARGET_DATABASE_URL:-${MIGRATOR_DATABASE_URL:-${DATABASE_URL:-$DEFAULT_DATABASE_URL}}}"
export M7_SOURCE_DATABASE_URL="${M7_SOURCE_DATABASE_URL:-${SUPABASE_DATABASE_URL:-$M7_TARGET_DATABASE_URL}}"
export M7_STORAGE_DATABASE_URL="${M7_STORAGE_DATABASE_URL:-$M7_TARGET_DATABASE_URL}"
export M7_CHECKPOINT_TABLE="${M7_CHECKPOINT_TABLE:-migration_sync_checkpoints}"
export M7_PIPELINE_NAME="${M7_PIPELINE_NAME:-default}"
export M7_GATE_RUN_MIGRATION_DRY_RUN="${M7_GATE_RUN_MIGRATION_DRY_RUN:-1}"
export M7_GATE_RUN_INCREMENTAL_DRY_RUN="${M7_GATE_RUN_INCREMENTAL_DRY_RUN:-1}"
export M7_GATE_RUN_DB_RECONCILE="${M7_GATE_RUN_DB_RECONCILE:-1}"
export M7_GATE_RUN_DUAL_READ="${M7_GATE_RUN_DUAL_READ:-1}"
export M7_GATE_RUN_STORAGE_RECONCILE="${M7_GATE_RUN_STORAGE_RECONCILE:-1}"
export M7_GATE_RUN_LAG_VERIFY="${M7_GATE_RUN_LAG_VERIFY:-1}"

export S3_ENDPOINT="${S3_ENDPOINT:-${M7_STORAGE_S3_ENDPOINT:-$DEFAULT_S3_ENDPOINT}}"
export S3_ACCESS_KEY_ID="${S3_ACCESS_KEY_ID:-minioadmin}"
export S3_SECRET_ACCESS_KEY="${S3_SECRET_ACCESS_KEY:-minioadmin}"
export S3_BUCKET="${S3_BUCKET:-agentifui}"
export S3_ENABLE_PATH_STYLE="${S3_ENABLE_PATH_STYLE:-1}"

pnpm m7:gate:report
