#!/usr/bin/env bash
set -euo pipefail

export M8_DRY_RUN="${M8_DRY_RUN:-0}"
export M8_ENFORCE_WAIT="${M8_ENFORCE_WAIT:-1}"
export M8_GATE_ROLLOUT_DRY_RUN="${M8_GATE_ROLLOUT_DRY_RUN:-$M8_DRY_RUN}"
export M8_GATE_ROLLBACK_DRY_RUN="${M8_GATE_ROLLBACK_DRY_RUN:-$M8_DRY_RUN}"
export M8_METRICS_STRICT="${M8_METRICS_STRICT:-1}"
export M8_METRICS_REQUIRE_ALL_SIGNALS="${M8_METRICS_REQUIRE_ALL_SIGNALS:-1}"
export M8_REQUIRE_SWITCH_COMMAND="${M8_REQUIRE_SWITCH_COMMAND:-1}"
export M8_REQUIRE_VERIFY_TRAFFIC_COMMAND="${M8_REQUIRE_VERIFY_TRAFFIC_COMMAND:-1}"
export M8_REQUIRE_SMOKE="${M8_REQUIRE_SMOKE:-1}"
export M8_REQUIRE_RECONCILE="${M8_REQUIRE_RECONCILE:-1}"
export M8_REQUIRE_ROLLBACK_COMMAND="${M8_REQUIRE_ROLLBACK_COMMAND:-1}"
export M8_ALLOW_DRY_RUN_PASS="${M8_ALLOW_DRY_RUN_PASS:-0}"
export M8_REQUIRE_100_STABILITY="${M8_REQUIRE_100_STABILITY:-1}"
export M8_REQUIRED_100_STABILITY_MINUTES="${M8_REQUIRED_100_STABILITY_MINUTES:-1440}"

pnpm gate:quality:verify
node scripts/m8-gate-verify.mjs
